name: 'Tests: E2E'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key:
            # prettier-ignore
            ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: |
          pnpm install
          npx playwright install --with-deps
      - name: Run e2e tests
        run: |
          PUBLIC_FATHOM_ID=${{ secrets.PUBLIC_FATHOM_ID }}
          PUBLIC_FATHOM_URL=${{ secrets.PUBLIC_FATHOM_URL }}
          AIRTABLE_TOKEN=${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE_ID=${{ secrets.AIRTABLE_BASE_ID }}
          EMAIL_SIGNUP_API_KEY=${{ secrets.EMAIL_SIGNUP_API_KEY }}
          FATHOM_API_KEY=${{ secrets.FATHOM_API_KEY }}
          pnpm run test:e2e
