name: 'Pull Request Checks'
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  pr-checks:
    name: Run pull request checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
